### ISSUE TITLE
How this module is different from using server.close?

### ISSUE THREAD

**Issue by stalniy** [thedillonb/http-shutdown#11]
According to Net module documentation https://nodejs.org/api/net.html#net_server_close_callback

> Stops the server from accepting new connections and keeps existing connections. This function is asynchronous, the server is finally closed when all connections are ended and the server emits a 'close' event. The optional callback will be called once the 'close' event occurs. Unlike that event, it will be called with an Error as its only argument if the server was not open when it was closed.

So, how is it better than using native `close` function?

**Comment by thedillonb** [comment]
https://github.com/nodejs/node/issues/2642 is a good read. It has to do with the keep-alive connections. You can basically keep making requests on a connection that is marked as a "keep-alive".
