### ISSUE TITLE
req.socket different than the socket on connection?

### ISSUE THREAD

**Issue by ehynds** [thedillonb/http-shutdown#3]
I didn't dig into this too deeply, but I noticed that the sockets attached to `req` in the `server.on('request', fn)` event handler have an undefined `_connectionId` property. This makes me wonder if the destroy logic is working properly and if those sockets are making it into the `connections` object. Not sure if the socket on connection is being passed by reference into the request handler?

**Comment by LinearSpoon** [comment]
I just found this problem as well. I was able to use `server.on('secureConnection')` to get the correct socket for requests over HTTPS.

**Comment by thedillonb** [comment]
This has been resolved via #6 - bad book keeping by me.
